version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 58081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH: false
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
  #     ME_CONFIG_MONGODB_URL: ${MONGO_URL}
  #   depends_on:
  #     - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URL: ${MONGO_URL}
    ports:
      - "63000:3000"
    depends_on:
      - mongo